#!/bin/bash

for test in $(ls inputdir/*.txt)
do
    echo InputFile=$test NumThreads=1
    ./tecnicofs-nosync inputdir/$test $outputdir/$test-1.txt 1 1
    
    for e in $(seq 2 ${3})
    do
        echo InputFile=$test NumThreads=$e
        ./tecnicofs-mutex inputdir/$test $outputdir/$test-$e.txt e numbuckets
